server:
  port: 8081

spring:
  application:
    name: msvc-order

  config:
    import: optional:configserver:http://localhost:8761


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka